name: m3ex_ui_package
description: "Material 3 Expressive widgets package for all Crystal apps."
version: 1.2.0
homepage:

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_styled_toast: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
